binary_build_commands: make cosign
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.20
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: make test
tests:
- as: test
  commands: make test
  container:
    from: src
zz_generated_metadata:
  branch: release-next
  org: securesign
  repo: cosign
